version: "3.3"
services:
  workspace:
    build: ./docker/centos6
    stdin_open: true
    tty: true 
    ports:
      - "80:80"
    volumes:
      - ${DATA_SRC:-..}:/var/www/html
      - ./docker/httpd/conf.d:/etc/httpd/conf.d

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_NAME:-default}
      MYSQL_USER: ${DB_USER:-default}
      MYSQL_PASSWORD: ${DB_PASS:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-root}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ${DB_DATA:-./datadir}:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
      
  adminer:
    image: adminer:4.2
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
